# Start with a MySQL base image
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=nov2024
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=root

# Expose the MySQL port
EXPOSE 3306
